ASP.NETCoreGruppProjektDaniel_John/Pages/Admin/ManageUsers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ASP.NETCoreGruppProjektDaniel_John.Data;
using ASP.NETCoreGruppProjektDaniel_John.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;



namespace ASP.NETCoreGruppProjektDaniel_John.Pages
{
    [Authorize(Roles="admin")]
    public class ManageUsersModel : PageModel
    {
        private readonly ASP.NETCoreGruppProjektDaniel_John.Data.EventDbContext _context;
        private readonly UserManager<MyUser> _userManager;

        public ManageUsersModel(ASP.NETCoreGruppProjektDaniel_John.Data.EventDbContext context, UserManager<MyUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        public IList<Event> Event { get; set; }

        public IList<MyUser> MyUser { get; set; }


        public async Task OnGetAsync()
        {
            Event = await _context.Events.ToListAsync();
            MyUser = await _context.Users.ToListAsync();
        }

        public async Task<IActionResult>OnPostAddAsync(string UserName)
        {
            var User = await _context.Users.Where(u => u.UserName == UserName).FirstOrDefaultAsync();
            await _userManager.AddToRoleAsync(User, "organizer");  // UserName är null
            // User.RoleIsOrganizer = true;
            await _context.SaveChangesAsync();

            Event = await _context.Events.ToListAsync();
            MyUser = await _context.Users.ToListAsync();
            return Page();
        }

        public async Task<IActionResult> OnPostRemoveAsync(string UserName)
        {
            var User = await _context.Users.Where(u => u.UserName == UserName).FirstOrDefaultAsync();
            await _userManager.RemoveFromRoleAsync(User, "organizer");  // UserName är null...
            // User.RoleIsOrganizer = false;
            await _context.SaveChangesAsync();

            Event = await _context.Events.ToListAsync();
            MyUser = await _context.Users.ToListAsync();
            return Page();
        }
    }
}

ASP.NETCoreGruppProjektDaniel_John/Pages/Admin/Nuclear.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP.NETCoreGruppProjektDaniel_John.Data;
using ASP.NETCoreGruppProjektDaniel_John.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ASP.NETCoreGruppProjektDaniel_John.Pages.Admin
{
    [Authorize(Roles = "admin")]
    public class NuclearModel : PageModel
    {
        private readonly EventDbContext _context;
        private readonly UserManager<MyUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public NuclearModel(
            EventDbContext context,
            UserManager<MyUser> userManager,
            RoleManager<IdentityRole> roleManager
            )
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public async Task OnPostAsync()
        {
            await _context.SeedAsync(_userManager, _roleManager, true);
        }
    }
}

ASP.NETCoreGruppProjektDaniel_John/Pages/Admin/ManageUsers.cshtml
@page
@model ASP.NETCoreGruppProjektDaniel_John.Pages.ManageUsersModel
@using ASP.NETCoreGruppProjektDaniel_John.Models
@inject UserManager<MyUser> userManager
@{
    ViewData["Title"] = "ManageUsers";
}

<h1>Manage Users</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                UserName
            </th>
            <th>
                Email
            </th>
            <th>
                Is Organizer
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.MyUser)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @if (await userManager.IsInRoleAsync(item, "organizer"))
                    {
                        <form method="post" >
                            <input type="checkbox" checked disabled/>
                        </form>
                    }
                else
                    {
                <form method="post">
                    <input type="checkbox" disabled/>
                </form>  


                    }

<td>
                <td>

                    @if (await userManager.IsInRoleAsync(item, "organizer"))
                    {
                        <form method="post" asp-route-UserName="@item.UserName" asp-page-handler="Remove">
                            <button type="submit">Remove organizer</button>
                        </form>
                    }
                    else
                    {
                        <form method="post" asp-route-UserName="@item.UserName" asp-page-handler="Add">
                            <button type="submit">Make organizer</button>
                        </form>
                    }
                <td>
                   
                </td>
            </tr>
        }
    </tbody>
</table>

ASP.NETCoreGruppProjektDaniel_John/Pages/Admin/Nuclear.cshtml
@page
@model ASP.NETCoreGruppProjektDaniel_John.Pages.Admin.NuclearModel
@{
    ViewData["Title"] = "Nuclear";
}
<h1>Nuclear Option</h1>
<h4>Reset the database?</h4>
<br />
<div>
    <form method="post">
        <input type="submit" name="test" value="Nuclear Option!" style="background-color:red;" />
    </form>
</div>
<br />

<div>
    <a asp-page="/Index">Back to Index</a>
</div>